services:

  backend:
    build:
      context: .
    volumes:
      - ./:/backend
    networks:
      - web_app_network
    ports:
      - '8000:8000'
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - redis

  redis:
    image: redis:7.0.11-alpine
    hostname: redis
    volumes:
      - type: volume
        source: data_redis
        target: /data
    networks:
      - web_app_network
    restart: always

networks:
  web_app_network:
    driver: bridge

volumes:
  data_redis: